accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/', views.signup_view, name="signup"),
    url(r'^login/', views.login_view, name="login"),
    url(r'^logout', views.logout_view, name="logout"),
    url(r'^profile/$', views.update_profile),
    url(r'^dashboard/$', views.dashboard, name="dashboard"),

]

articles/urls.py
from django.conf.urls import url
from . import views

app_name = 'articles'

urlpatterns = [

    url(r'^$', views.article_list, name="list"),
    url(r'^create/$', views.article_create, name="create"),

    url(r'^comments/$', views.article_post_comments, name="post_comments"),
    url(r'^reply/$', views.articles_comments_reply, name="reply_comments"),
    url(r'^search/$', views.search_article, name="search_article"),


    url(r'^edit/(?P<slug>[\w-]+)/$', views.article_edit, name="edit"),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name="detail"), # Put it a last otherwise it will match to other routes conditions
]

blog/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^about/$', views.about),
    url(r'^$', views.homepage, name="home"),
    url(r'^articles/', include('articles.urls')),
    url(r'^accounts/', include('accounts.urls')),

    # url(r'^accounts/', include('social_django.urls', namespace='social')),
    # url(r'^accounts/', include('django.contrib.auth.urls', namespace='auth')),

    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <--
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,unique=True, null=False, db_index=True)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

accounts/forms.py
from django.shortcuts import redirect, HttpResponseRedirect
from django.contrib.auth import logout
from django.contrib.auth.models import User

from .models import Profile

# from . import models
from django import forms

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio','location','birth_date')

accounts/views.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.http import HttpResponse

# Create your views here.
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import logout, login
from django.http import HttpResponseRedirect
from django.db import transaction
from .models import Profile
from .forms import UserForm,ProfileForm
from articles.models import Article

# get signup/registration form 
def signup_view(request):

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # login(request, user)
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('articles:list')
    else:
        form = UserCreationForm()

    return render(request, 'accounts/signup.html', { 'form': form })

# Get the login view
def login_view(request):

    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', { 'form': form })

# Logout the user from app
def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')


# Show dashboard
@login_required(login_url="/accounts/login/")
def dashboard(request):
    user_id = request.user.id

    user_form = UserForm(instance=request.user)
    # return HttpResponse(user_id)
    # articles = Article.objects.all().order_by('date') 
    # articles =  Article.objects.get(author=user_id)

    articles = Article.objects.filter(author=user_id).values()

    # return HttpResponse(articles)

    return render(request, 'accounts/dashboard.html', { 'articles': articles, 'user_form': user_form })


@login_required
@transaction.atomic
def update_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return HttpResponseRedirect('/')
        else:
            return HttpResponseRedirect('/')
            # messages.error(request, ('Please correct the error below.'))
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'accounts/dashboard.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

templates/accounts/dashboard.html
{% extends 'main_layout.html' %}

{% load static from staticfiles %}

{% block title %}
	Dashboard1
{% endblock %}


{% block css %}

<style type="text/css">
	
	@media (min-width: 840px){
		.mdl-grid {
		     padding: 0px; 
		}
		.mdl-cell {
		     margin: 0px; 
		}
	}

	.mdl-card {
		border-radius: 0px;
	}
	
</style>
	
{% endblock %}

{% block before_main %}

{% endblock %}

{% block content %}

	<div class="mdl-grid" id="dashboard_contant">
        <div class="mdl-card mdl-shadow--2dp mdl-cell mdl-cell--2-col mdl-cell--hide-tablet mdl-cell--hide-phone dashboard_tabs">
 			<a class="mdl-navigation__link" href="/"><i class=" material-icons orange600" role="presentation">home</i>Home</a>
 			<a class="mdl-navigation__link" id="my_profile" href="javascript:void(0);" v-on:click="show_dashboard_contant"><i class=" material-icons orange600" role="presentation">face</i>My Profile</a>
 			<a class="mdl-navigation__link" id="my_articles" href="javascript:void(0);" v-on:click="show_dashboard_contant"><i class=" material-icons" role="presentation">face</i>My Articles</a>
          	<a class="mdl-navigation__link" href="javascript:void(0);"><i class=" material-icons" role="presentation">inbox</i>Inbox</a>
          	<a class="mdl-navigation__link" href="javascript:void(0);"><i class=" material-icons" role="presentation">delete</i>Trash</a>
          	<a class="mdl-navigation__link" href="javascript:void(0);"><i class=" material-icons" role="presentation">report</i>Spam</a>
          	<a class="mdl-navigation__link" href="javascript:void(0);"><i class=" material-icons" role="presentation">forum</i>Forums</a>
          	<a class="mdl-navigation__link" href="javascript:void(0);"><i class=" material-icons" role="presentation">flag</i>Updates</a>
          	<a class="mdl-navigation__link" href="javascript:void(0);"><i class=" material-icons" role="presentation">local_offer</i>Promos</a>

        </div>

        <div class="mdl-card mdl-shadow--3dp mdl-cell mdl-cell--10-col mdl-cell--hide-tablet mdl-cell--hide-phone  background-color">
        	<div class="mdl-grid " style="width: 100%;">
        	<div class="mdl-cell--1-col">
        	</div>
        	<div class=" mdl-cell--10-col">

        		<!-- view my articles -->
        		<div id="show_my_articles">
		        	<table class="mdl-data-table mdl-js-data-table mdl-data-table--selectable mdl-shadow--2dp" style="width: 100%;">
					  <thead>
					    <tr>
					      <th class="mdl-data-table__cell--non-numeric">Article Title</th>
					      <th>Slug</th>
					      <th>Posted On</th>
					    </tr>
					  </thead>
					  <tbody>
					  	{% for article in articles %}
						  	<tr>
						      <td class="mdl-data-table__cell--non-numeric"><a href="{% url 'articles:detail' slug=article.slug %}" target="_blank">{{article.title}}</a></td>
						      <td>{{article.slug}}</td>
						      <td>
						      	{{article.date}}
						      	

					            <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon mdl-color--white pull-right" role="presentation" id="delete_tt_{{article.slug}}" >
					                <i class="material-icons">delete</i>
					                <div class="mdl-tooltip mdl-tooltip--right" for="delete_tt_{{article.slug}}">
					                  delete
					                </div>
					            </button>
					            <a href="{% url 'articles:edit' slug=article.slug %}" target="_blank">
					            <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon mdl-color--white pull-right" role="presentation" id="edit_tt_{{article.slug}}"  >
					                <i class="material-icons">create</i>
					                <div class="mdl-tooltip mdl-tooltip--left" for="edit_tt_{{article.slug}}">
					                  edit
					                </div>
					            </button>
					            </a>
						      </td>
						    </tr>
		        		{% endfor %}
					  </tbody>
					</table>
				</div>



				<!-- view mmy profile -->
				<div id="show_my_profile" style="margin-top:20px;">

					
					<div class="mdl-data-table mdl-js-data-table mdl-data-table--selectable mdl-shadow--2dp" style="width: 100%;">

						<!-- {{ user_form }}
						{{ profile_form }} -->
					</div>

				</div>

			</div>
        	<div class="mdl-cell--1-col"></div>

        	<!-- {{ profile_form }} -->

        </div>

    </div>
{% endblock %}

{% block before_body %}

	<script src="{% static 'js/app.js' %}"></script>

{% endblock %}

templates/accounts/login.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <title>
      </title>
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <link rel="stylesheet" href="{% static 'style.css' %}">
      <!--<link rel="stylesheet" href="{% static 'floating-labels.css' %}">-->
      <link rel="stylesheet" href="{% static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">
      <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
      <link rel="stylesheet" href="{% static 'css/main.css' %}">
   </head>
   <body>
      <!--<form method="post" role="form" action="{% url 'accounts:login' %}">-->
      <!--{% csrf_token %}-->
      <!--{{form}}-->
      <!--{% if request.GET.next %}-->
      <!--<input type="hidden" name="next" value="{{request.GET.next}}">-->
      <!--{% endif %}-->
      <!--<button type="submit" value="login">submit</button>-->
      <!--</form>-->
      <!--<form class="form-signin" role="form" action="{% url 'accounts:login' %}" method="POST">-->
      <!--{% csrf_token %}-->
      <!--{% if request.GET.next %}-->
      <!--<input type="hidden" name="next" value="{{request.GET.next}}">-->
      <!--{% endif %}-->
      <!--<div class="form-label-group">-->
      <!--<input type="text" id="inputEmail" class="form-control" placeholder="Email address" required="" autofocus="" name="username">-->
      <!--<label for="inputEmail">Email address</label>-->
      <!--</div>-->
      <!--<div class="form-label-group">-->
      <!--<input type="password" id="inputPassword" class="form-control" placeholder="Password" required="" name="password">-->
      <!--<label for="inputPassword">Password</label>-->
      <!--</div>-->
      <!--<div class="checkbox mb-3">-->
      <!--<label>-->
      <!--<input type="checkbox" value="remember-me"> Remember me-->
      <!--</label>-->
      <!--</div>-->
      <!--<button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>-->
      <!--<a href="" class="">Gmail</a>-->
      <!--<button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>-->
      <!--</form>-->
      <div class="limiter">
         <div class="container-login100" style="background-image: url('images/bg-01.jpg');">
            <div class="wrap-login100">
               <form class="login100-form validate-form" role="form" action="{% url 'accounts:login' %}" method="POST">
                  {% csrf_token %}
                  {% if request.GET.next %}
                  <input type="hidden" name="next" value="{{request.GET.next}}">
                  {% endif %}
                  <span class="login100-form-logo">
                  <i class="zmdi zmdi-landscape"></i>
                  </span>
                  <!--<span class="login100-form-title p-b-34 p-t-27">-->
                  <!--Log in-->
                  <!--</span>-->
                  <div class="wrap-input100 validate-input" data-validate = "Enter username">
                     <input class="input100" type="text" name="username" placeholder="Username">
                     <span class="focus-input100" data-placeholder="&#xf207;"></span>
                  </div>
                  <div class="wrap-input100 validate-input" data-validate="Enter password">
                     <input class="input100" type="password" name="password" placeholder="Password">
                     <span class="focus-input100" data-placeholder="&#xf191;"></span>
                  </div>
                  <div class="contact100-form-checkbox">
                     <input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
                     <label class="label-checkbox100" for="ckb1">
                     Remember me
                     </label>
                     <div class="text-right p-t-90">
                        <a class="txt1" href="#">
                        Forgot Password?
                        </a>
                     </div>
                  </div>
                  <div class="container-login100-form-btn">
                     <button class="login100-form-btn" type="submit">
                     Login
                     </button>
                  </div>
                  <div class="container-login100-form-btn">
                     <button class="login100-form-btn" type="submit">
                     <a href="{% url 'accounts:signup' %}">SignUp</a>
                     </button>
                  </div>
                  <div class="flex-c-m">
                     <a href="#" class="login100-social-item bg1">
                     <i class="fa fa-facebook"></i>
                     </a>
                     <!-- <a href="#" class="login100-social-item bg2">
                     <i class="fa fa-twitter"></i>
                     </a> -->
                     <a class="login100-social-item bg2" href="{% url 'social:begin' 'github' %}">
                        <i class="fa fa-github"></i>
                     </a>
                     <a class="login100-social-item bg3" href="{% url 'social:begin' 'google-oauth2' %}?next=/">
                     <i class="fa fa-google"></i>
                     </a>
                     
                  </div>
               </form>
            </div>
         </div>
      </div>
   </body>
</html>

templates/accounts/signup.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!--<link rel="stylesheet" href="{% static 'floating-labels.css' %}">-->

    <link rel="stylesheet" href="{% static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

</head>
<body>

    <!--<form method="post" role="form" action="{% url 'accounts:login' %}">-->

        <!--{% csrf_token %}-->
        <!--{{form}}-->
        <!--{% if request.GET.next %}-->
            <!--<input type="hidden" name="next" value="{{request.GET.next}}">-->
        <!--{% endif %}-->
        <!--<button type="submit" value="login">submit</button>-->

    <!--</form>-->

    <!--<form class="form-signin" role="form" action="{% url 'accounts:login' %}" method="POST">-->
        <!--{% csrf_token %}-->
        <!--{% if request.GET.next %}-->
            <!--<input type="hidden" name="next" value="{{request.GET.next}}">-->
        <!--{% endif %}-->

      <!--<div class="form-label-group">-->
        <!--<input type="text" id="inputEmail" class="form-control" placeholder="Email address" required="" autofocus="" name="username">-->
        <!--<label for="inputEmail">Email address</label>-->
      <!--</div>-->

      <!--<div class="form-label-group">-->
        <!--<input type="password" id="inputPassword" class="form-control" placeholder="Password" required="" name="password">-->
        <!--<label for="inputPassword">Password</label>-->
      <!--</div>-->

      <!--<div class="checkbox mb-3">-->
        <!--<label>-->
          <!--<input type="checkbox" value="remember-me"> Remember me-->
        <!--</label>-->
      <!--</div>-->
      <!--<button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>-->
        <!--<a href="" class="">Gmail</a>-->
        <!--<button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>-->
    <!--</form>-->

<div class="limiter">
		<div class="container-login100" style="background-image: url('images/bg-01.jpg');">
			<div class="wrap-login100">
                <!--<h2>Signup page</h2>-->

    <!--<form method="post" role="form" action="{% url 'accounts:signup' %}">-->
        <!--{% csrf_token %}-->
        <!--{{form}}-->

        <!--<button type="submit" value="signup">submit</button>-->

    <!--</form>-->
				<form class="login100-form validate-form" role="form" action="{% url 'accounts:signup' %}" method="POST">
					{% csrf_token %}

					{% if request.GET.next %}
            			<input type="hidden" name="next" value="{{request.GET.next}}">
        			{% endif %}

					<span class="login100-form-logo">
						<i class="zmdi zmdi-landscape"></i>
					</span>

					<!--<span class="login100-form-title p-b-34 p-t-27">-->
						<!--Log in-->
					<!--</span>-->

					<div class="wrap-input100 validate-input" data-validate = "Enter username">
						<input class="input100" type="text" name="username" placeholder="Username">
						<span class="focus-input100" data-placeholder="&#xf207;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<input class="input100" type="password" name="password1" required="" id="id_password1" placeholder="Password">
						<span class="focus-input100" data-placeholder="&#xf191;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<input class="input100" type="password" name="password2" required="" id="id_password2" placeholder="Confirm Password">
						<span class="focus-input100" data-placeholder="&#xf191;"></span>
					</div>


					<div class="container-login100-form-btn">
						<button class="login100-form-btn" type="submit" value="signup">
							Sign Up
						</button>
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn" type="button">
							<a href="{% url 'accounts:login' %}">Login</a>
						</button>
					</div>

					<div class="flex-c-m">
						<a href="#" class="login100-social-item bg1">
							<i class="fa fa-facebook"></i>
						</a>

						<a href="#" class="login100-social-item bg2">
							<i class="fa fa-twitter"></i>
						</a>

						<a class="login100-social-item bg3" href="{% url 'social:begin' 'google-oauth2' %}?next=/">
							<i class="fa fa-google"></i>
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>



</body>
</html>