articles/urls.py
from django.conf.urls import url
from . import views

app_name = 'articles'

urlpatterns = [

    url(r'^$', views.article_list, name="list"),
    url(r'^create/$', views.article_create, name="create"),

    url(r'^comments/$', views.article_post_comments, name="post_comments"),
    url(r'^reply/$', views.articles_comments_reply, name="reply_comments"),
    url(r'^search/$', views.search_article, name="search_article"),


    url(r'^edit/(?P<slug>[\w-]+)/$', views.article_edit, name="edit"),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name="detail"), # Put it a last otherwise it will match to other routes conditions
]

blog/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^about/$', views.about),
    url(r'^$', views.homepage, name="home"),
    url(r'^articles/', include('articles.urls')),
    url(r'^accounts/', include('accounts.urls')),

    # url(r'^accounts/', include('social_django.urls', namespace='social')),
    # url(r'^accounts/', include('django.contrib.auth.urls', namespace='auth')),

    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <--
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Article(models.Model):

    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    key_words = models.CharField(max_length=100)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE, related_name='user')
    up_vote = models.PositiveSmallIntegerField(null=True)
    allow_comments = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    visibility = models.CharField(max_length=20, blank=True)
    likes = models.PositiveSmallIntegerField(null=True)
    # add in thumbnail

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50]+"..."



class Comment(models.Model):

    comment = models.CharField(max_length=200)
    author  = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, default=None, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add = True)
    up_vote = models.PositiveSmallIntegerField(null=True)
    down_vote = models.PositiveSmallIntegerField(null=True)
    approved = models.PositiveSmallIntegerField(default=1)
    approved_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment



class ReplyOnComment(models.Model):

    reply = models.CharField(max_length=200)
    date = models.DateTimeField(auto_now_add = True)
    author  = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, default=None, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, default=None, on_delete=models.CASCADE)
    up_vote = models.PositiveSmallIntegerField(null=True)
    down_vote = models.PositiveSmallIntegerField(null=True)
    approved = models.PositiveSmallIntegerField(default=1)
    approved_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.reply

articles/forms.py
from django import forms
from . import models


# class CreateArticle(forms.ModelForm):
#     class Meta:
#         model = models.Article
#         fields = [ 'title', 'body', 'slug', 'thumb', 'key_words', 'visibility', 'allow_comments' ]


class CreateArticle(forms.ModelForm):
    # ...
    class Meta:
        model = models.Article
        fields = [ 'title', 'body', 'slug', 'thumb', 'key_words', 'visibility', 'allow_comments' ]

    def clean(self):
        cleaned_data = self.cleaned_data
        title = cleaned_data.get("title")
        body = cleaned_data.get("body")
        slug = cleaned_data.get("slug")
        key_words = cleaned_data.get("key_words")
        visibility = cleaned_data.get("visibility")
        allow_comments = cleaned_data.get("allow_comments")

        # if end_date and start_date:
        #     if end_date < start_date:
        #         msg = 'Event end date should not occur before start date.'
        #         self._errors['end_date'] = self.error_class([msg])
        #         del cleaned_data['end_date']

        # form.add_error('field_name', 'error_msg or ValidationError instance') If the field_name is None the error will be added to non_field_errors.
        
        # if end_date and start_date:
        # if end_date < start_date:
        #     self.add_error('end_date', 'Event end date should not occur before start date.')
            # You can use ValidationError as well
            # self.add_error('end_date', form.ValidationError('Event end date should not occur before start date.'))


        return cleaned_data


# class ArticleForm(forms.Form):

#     # Everything as before.
#     def clean(self):
#         cleaned_data = super(ArticleForm, self).clean()
#         title = cleaned_data.get("title")
#         body = cleaned_data.get("body")
#         slug = cleaned_data.get("slug")
#         key_words = cleaned_data.get("key_words")
#         visibility = cleaned_data.get("visibility")
#         allow_comments = cleaned_data.get("allow_comments")


class PostComment(forms.ModelForm):
	class Meta:
		model = models.Comment
		fields = [ 'comment' ]

articles/views.py
from django.shortcuts import render, redirect
from .models import Article, Comment, ReplyOnComment
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms
from django.db.models import Q

# Create your views here.


def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html', {'articles': articles})


def article_detail(request, slug):
    
    article = Article.objects.get(slug=slug)

    comments = Comment.objects.filter(article= article.id).select_related() 
    # return HttpResponse(comment)
    # [:1]
    # return article.author_set.all()
    # return HttpResponse(article.author_set.all())
    return render(request, 'articles/article_detail.html', {'article': article, 'comments' : comments})


@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # save to data db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', {'form': form})


@login_required(login_url="/accounts/login/")
def article_edit(request, slug):
    
    article = Article.objects.get(slug=slug)

    comments = Comment.objects.filter(article= article.id).select_related() 
    # return HttpResponse(comment)
    # [:1]
    # return article.author_set.all()
    # return HttpResponse(article.author_set.all())
    return render(request, 'articles/article_detail.html', {'article': article, 'comments' : comments})

def search_article(request):
    try:
        q = request.GET['search']
        # article = Article.objects.all().order_by('date')
        # article = Article.objects.filter(Q(title__search=q)) #| Q(slug__search=q) | Q(body__search=q))
        article = Article.objects.filter(title__icontains=q)
        # return article

        return render(request, 'articles/article_list.html', {'articles' : article, 'search': q })
    except KeyError:
        return render(request, 'articles/article_list.html')


@login_required(login_url="/accounts/login")
def article_post_comments(request):
   
    if request.method == 'POST':

        form = forms.PostComment(request.POST)

        # return HttpResponse(form.is_valid())
        # return HttpResponse(request.user)
        
        if form.is_valid():
            b = Comment.objects.create(comment=request.POST.get("comment"), article_id=request.POST.get("article_id"), author_id = request.user.id)
            b.save()
            # save to data db
            # instance = form.save(commit=False)
            # instance.author = request.user
            # instance.article = request.POST.get("article_id")
            # instance.save()
            # return redirect('articles:list')
    # else:
    #     form = forms.CreateArticle()
    article = Article.objects.get(id=request.POST.get("article_id"))
    # return redirect('articles:detail', {'article': article})
    return render(request, 'articles/article_detail.html', {'article': article})



def articles_comments_reply(request):
    return HttpResponse("hi")

templates/articles/article_create.html
{% extends 'main_layout.html' %}
{% block title %}
Create Your Article
{% endblock %}
{% block content %}

<!--<form class="site-form" name="" method="post" action="{% url 'articles:create' %}" enctype="multipart/form-data">-->
<!--{% csrf_token %}-->
<!--{{ form }}-->
<!--<button type="submit">create</button>-->
<!--</form>-->
<!-- <main class="mdl-layout__content "> -->

<form class="site-form create_article_form" id="create_article_form" role="form" name="create_article_form" method="post" action="{% url 'articles:create' %}" enctype="multipart/form-data">
{% csrf_token %}

   <div class="mdl-grid create_article_page">
      <div class="mdl-cell mdl-cell--1-col mdl-cell--hide-tablet mdl-cell--hide-phone"></div>
      <div class="mdl-cell mdl-cell--6-col mdl-cell--8-col-tablet mdl-cell--12-col-phone">

          {% if form.errors %}
              {% for field in form %}
                  {% for error in field.errors %}
                      <div class="alert alert-danger">
                          <strong>{{ error|escape }}</strong>
                      </div>
                  {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                  <div class="alert alert-danger">
                      <strong>{{ error|escape }}</strong>
                  </div>
              {% endfor %}
          {% endif %}

          <div class="demo-card-event mdl-card mdl-shadow--2dp">
              <!--<div class="mdl-card">-->
              <div class="mdl-card__title">
                    <h2 class="mdl-card__title-text">Create an Article</h2>
              </div>
         <!--<div class="mdl-cell mdl-cell&#45;&#45;4-col mdl-cell&#45;&#45;6-col-tablet">4 (6 tablet)</div>-->
         <!--<div class="mdl-cell mdl-cell&#45;&#45;2-col mdl-cell&#45;&#45;4-col-phone">2 (4 phone)</div>-->
         
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
               <input class="mdl-textfield__input" type="text" name="title" required="" id="id_title" maxlength="100">
               <label class="mdl-textfield__label" for="id_title">Title...</label>
            </div>
            <!--<div class="mdl-textfield mdl-js-textfield mdl-textfield&#45;&#45;floating-label">-->
            <!--<input class="mdl-textfield__input" type="text" name="title" id="id_title" required>-->
            <!--<label class="mdl-textfield__label" for="id_title">Text...</label>-->
            <!--</div>-->
            <div class="mdl-textfield mdl-js-textfield">
               <textarea class="mdl-textfield__input" type="text" name="body" id="id_body" rows="3" required=""></textarea>
               <label class="mdl-textfield__label" for="id_body">Text lines...</label>
            </div>
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
               <input class="mdl-textfield__input" type="text" name="slug" required="" id="id_slug" maxlength="50">
               <label class="mdl-textfield__label" for="id_slug">Slug</label>
            </div>
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
               <input class="mdl-textfield__input" type="file" name="thumb" id="id_thumb">
               <!--<label class="mdl-textfield__label" for="id_thumb">Slug</label>-->
            </div>
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
               <input class="mdl-textfield__input" type="text" name="key_words" required="" id="id_key_words" maxlength="100">
               <label class="mdl-textfield__label" for="id_key_words">Key Words</label>
            </div>
            <!--<button type="submit">create</button>-->
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
               <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" type="submit">
               Create
               </button>
            </div>
         
          </div>
      </div>
      <div class="mdl-cell mdl-cell--3-col mdl-cell--8-col-tablet mdl-cell--12-col-phone">

          <div class="mdl-card demo-card-event mdl-shadow--2dp" style="min-height:auto;">
            <div class="mdl-card__title">
              <h2 class="mdl-card__title-text">Visibility</h2>
            </div>
            <div class="mdl-card__supporting-text">
              <label class="mdl-radio mdl-js-radio mdl-js-ripple-effect" for="option-1">
                <input type="radio" id="option-1" class="mdl-radio__button" name="visibility" value="public" checked required>
                <span class="mdl-radio__label">Public</span>
              </label>
              <label class="mdl-radio mdl-js-radio mdl-js-ripple-effect" for="option-2">
                <input type="radio" id="option-2" class="mdl-radio__button" name="visibility" value="private">
                <span class="mdl-radio__label">Private</span>
              </label>
            </div>


            <ul class="demo-list-control mdl-list">
              <!-- <li class="mdl-list__item">
                <span class="mdl-list__item-primary-content">
                  <i class="material-icons  mdl-list__item-avatar">person</i>
                  Bryan Cranston
                </span>
                <span class="mdl-list__item-secondary-action">
                  <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="list-checkbox-1">
                    <input type="checkbox" id="list-checkbox-1" class="mdl-checkbox__input" checked />
                  </label>
                </span>
              </li>
              <li class="mdl-list__item">
                <span class="mdl-list__item-primary-content">
                  <i class="material-icons  mdl-list__item-avatar">person</i>
                  Aaron Paul
                </span>
                <span class="mdl-list__item-secondary-action">
                  <label class="demo-list-radio mdl-radio mdl-js-radio mdl-js-ripple-effect" for="list-option-1">
                    <input type="radio" id="list-option-1" class="mdl-radio__button" name="options" value="1" checked />
                  </label>
                </span>
              </li> -->
              <li class="mdl-list__item">
                <span class="mdl-list__item-primary-content">
                  <!-- <i class="material-icons  mdl-list__item-avatar">person</i> -->
                  Comments
                </span>
                <span class="mdl-list__item-secondary-action">
                  <label class="mdl-switch mdl-js-switch mdl-js-ripple-effect" for="allow_comments">
                    <input type="checkbox" id="allow_comments" class="mdl-switch__input" name="allow_comments" checked/>
                  </label>
                </span>
              </li>
            </ul>

          </div>
      </div>

   </div>
  </form>

<!-- </main> -->
{% endblock %}
{% block before_body %}
{% endblock %}

templates/articles/article_detail.html
{% extends 'main_layout.html' %}

{% load static from staticfiles %}

{% block title %}
    {{article.title}}
{% endblock %}

{% block content %}

<!--<div class="image-ribbon">-->

    <!--<img src="{{ article.thumb.url}}">-->
<!--</div>-->
      <!--<main class="main-detail mdl-layout__content">-->
        <!--<div class="detail-container mdl-grid">-->
          <!--<div class="mdl-cell mdl-cell&#45;&#45;2-col mdl-cell&#45;&#45;hide-tablet mdl-cell&#45;&#45;hide-phone"></div>-->
          <!--<div class="detail-content mdl-color&#45;&#45;white mdl-shadow&#45;&#45;4dp content mdl-color-text&#45;&#45;grey-800 mdl-cell mdl-cell&#45;&#45;8-col">-->

            <!--<h3>{{article.title}}</h3>-->

              <!--<p>-->
                <!--{{article.body}}-->
              <!--</p>-->
              <!--<p>{{article.date}}</p>-->
          <!--</div>-->
        <!--</div>-->
      <!--</main>-->
      
<div class="detail_article detail_article--blogpost mdl-layout mdl-js-layout has-drawer is-upgraded">
        <!-- <main class="mdl-layout__content"> -->
        <div class="demo-back">
          <a class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon" href="/" title="go back" role="button">
            <i class="material-icons" role="presentation">arrow_back</i>
          </a>
        </div>
        <div class="detail_article__posts mdl-grid">
          <div class="mdl-card mdl-shadow--4dp mdl-cell mdl-cell--12-col" >
            <div class="mdl-card__media mdl-color-text--grey-50" style="background-image:url({{ article.thumb.url}})">
              <h3>{{article.title}}</h3>
            </div>
            <div class="mdl-color-text--grey-700 mdl-card__supporting-text meta">
              <div class="minilogo"></div>
              <div>
                <strong>{{article.author.first_name}} {{article.author.last_name}}</strong>
                <span>{{article.date}}</span>
              </div>
              <div class="section-spacer"></div>
              <div class="meta__favorites">
                425 <i class="material-icons" role="presentation">favorite</i>
                <span class="visuallyhidden">favorites</span>
              </div>
              <div>
                <i class="material-icons" role="presentation" id="bookmark_tt">bookmark</i>
                <span class="visuallyhidden">bookmark</span>
                <div class="mdl-tooltip" for="bookmark_tt">
                  Bookmark this article
                </div>
              </div>
              <div>
                <i class="material-icons" role="presentation" id="share_tt" >share</i>
                <span class="visuallyhidden">share</span>
                <!-- Multiline Tooltip -->
                <div class="mdl-tooltip" for="share_tt">
                Share your content<br>via social media
                </div>

              </div>
            </div>
            <div class="mdl-color-text--grey-700 mdl-card__supporting-text">

              {{article.body}}

            </div>


            {% if article.allow_comments == 1 %}
            <div class="mdl-color-text--primary-contrast mdl-card__supporting-text comments">
              <!-- Add a comment  -->
              <form class="site-form post_comments_form" id="post_comments_form" name="post_comments_form" method="post" action="{% url 'articles:post_comments' %}" >
                {% csrf_token %}
                <input type="hidden" name="article_id" value="{{article.id}}">
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                  <textarea rows=2 class="mdl-textfield__input" id="comment" name="comment"></textarea>
                  <label for="comment" class="mdl-textfield__label">Join the discussion</label>
                </div>
                <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon" type="submit">
                  <i class="material-icons" role="presentation">check</i><span class="visuallyhidden">add comment</span>
                </button>
              </form>

              {% for comment in comments %}
                
              <div class="comment mdl-color-text--grey-700">
                <header class="comment__header">
                  <img src="{% static 'images/user.jpg' %}" class="comment__avatar">
                  <div class="comment__author">
                    <strong>{{comment.author.first_name }}</strong>
                    <span>{{comment.date}}</span>
                  </div>
                </header>
                <div class="comment__text">
                  {{comment.comment }}
                </div>
                <nav class="comment__actions">
                  <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
                    <i class="material-icons" role="presentation">thumb_up</i><span class="visuallyhidden">like comment</span>
                  </button>
                  <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
                    <i class="material-icons" role="presentation">thumb_down</i><span class="visuallyhidden">dislike comment</span>
                  </button>
                  <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
                    <i class="material-icons" role="presentation">share</i><span class="visuallyhidden">share comment</span>

                  </button>
                <!-- </nav>
                <div class="comment__answers">
                  <div class="comment">
                    <div class="mdl-color-text--primary-contrast mdl-card__supporting-text comments">
                      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                        <textarea rows=1 class="mdl-textfield__input" id="comment" name="comment"></textarea>
                        <label for="comment" class="mdl-textfield__label">Join the discussion</label>
                      </div>
                      <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon" type="submit">
                        <i class="material-icons" role="presentation">check</i><span class="visuallyhidden">add comment</span>
                      </button>
                    </div>
                  </div>
                </div> -->

                
                <!-- <div class="comment__answers">
                  <div class="comment">
                    <header class="comment__header">
                      <img src="images/co2.jpg" class="comment__avatar">
                      <div class="comment__author">
                        <strong>John Dufry</strong>
                        <span>2 days ago</span>
                      </div>
                    </header>
                    <div class="comment__text">
                      Yep, agree!
                    </div>
                    <nav class="comment__actions">
                      <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
                        <i class="material-icons" role="presentation">thumb_up</i><span class="visuallyhidden">like comment</span>
                      </button>
                      <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
                        <i class="material-icons" role="presentation">thumb_down</i><span class="visuallyhidden">dislike comment</span>
                      </button>
                      <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
                        <i class="material-icons" role="presentation">share</i><span class="visuallyhidden">share comment</span>
                      </button>
                    </nav>
                  </div>
                </div> -->

              </div>
              {% endfor %}
            </div>

            {% endif %}

          </div>

          <nav class="demo-nav mdl-color-text--grey-50 mdl-cell mdl-cell--12-col">
            <a href="index.html" class="demo-nav__button">
              <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon mdl-color--white mdl-color-text--grey-900" role="presentation" id="previous_tt">
                <i class="material-icons">arrow_back</i>
                <div class="mdl-tooltip" for="previous_tt">
                  previous article
                </div>
              </button>
              Newer
            </a>
            <div class="section-spacer"></div>
            <a href="index.html" class="demo-nav__button">
              Older
              <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon mdl-color--white mdl-color-text--grey-900" role="presentation" id="next_tt">
                <i class="material-icons">arrow_forward</i>
                <div class="mdl-tooltip" for="next_tt">
                  next article
                </div>
              </button>
            </a>
          </nav>
        </div>

      <!-- </main> -->
      <div class="mdl-layout__obfuscator"></div>
</div>
{% endblock %}

{% block before_body %}
{% endblock %}

templates/articles/article_list.html
{% extends 'main_layout.html' %}
{% block title %}
List of all articles
{% endblock %}
{% block content %}
<!-- Wide card with share menu button -->
<!-- <main class="mdl-layout__content "> -->
   <div class="page-content article_list_container">
      <div class="mdl-grid">
         <div class="mdl-cell mdl-cell--2-col mdl-cell--hide-tablet mdl-cell--hide-phone"></div>
         <div class="mdl-cell mdl-cell--8-col mdl-cell--12-col-tablet mdl-cell--12-col-phone">
            {% for article in articles %}
            <div class="demo-card-wide mdl-card mdl-shadow--2dp">
               <div class="mdl-card__title" style="background-image:url({{ article.thumb.url}});">
                  <!--<img src="{{ article.thumb.url}}" style=" height: inherit;width:100%;">-->
                  <a href="{% url 'articles:detail' slug=article.slug %}" target="_blank">
                     <h2 class="mdl-card__title-text">{{article.title}}</h2>
                  </a>
               </div>
               <div class="mdl-card__supporting-text">
                  {{article.snippet}} <span>{{article.date}}</span>
               </div>
               <!--<div class="mdl-card__actions mdl-card&#45;&#45;border">-->
               <!--<a class="mdl-button mdl-button&#45;&#45;colored mdl-js-button mdl-js-ripple-effect">-->
               <!--{{article.date}}-->
               <!--</a>-->
               <!--</div>-->
               <div class="mdl-card__menu">
                  <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
                  <i class="material-icons">share</i>
                  </button>
               </div>
            </div>
            {% endfor %}
         </div>
      </div>
   </div>
<!-- </main> -->
{% endblock %}
{% block before_body %}
{% endblock %}

templates/articles/home.html
{% extends 'main_layout.html' %}

{% block title %}
Homepage
{% endblock %}

{% block content %}



{% endblock %}

{% block before_body %}
{% endblock %}