accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/', views.signup_view, name="signup"),
    url(r'^login/', views.login_view, name="login"),
    url(r'^logout', views.logout_view, name="logout"),
    url(r'^profile/$', views.update_profile),
    url(r'^dashboard/$', views.dashboard, name="dashboard"),

]

articles/urls.py
from django.conf.urls import url
from . import views

app_name = 'articles'

urlpatterns = [

    url(r'^$', views.article_list, name="list"),
    url(r'^create/$', views.article_create, name="create"),

    url(r'^comments/$', views.article_post_comments, name="post_comments"),
    url(r'^reply/$', views.articles_comments_reply, name="reply_comments"),
    url(r'^search/$', views.search_article, name="search_article"),


    url(r'^edit/(?P<slug>[\w-]+)/$', views.article_edit, name="edit"),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name="detail"), # Put it a last otherwise it will match to other routes conditions
]

blog/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^about/$', views.about),
    url(r'^$', views.homepage, name="home"),
    url(r'^articles/', include('articles.urls')),
    url(r'^accounts/', include('accounts.urls')),

    # url(r'^accounts/', include('social_django.urls', namespace='social')),
    # url(r'^accounts/', include('django.contrib.auth.urls', namespace='auth')),

    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <--
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader, context

def about(request):
    # template = loader.get_template('blog/about.html')
    #return HttpResponse(template.render())
    context = ""
    return render(request, 'blog/about.html')
    # return render(request, template)

def homepage(request):
    # return HttpResponse("homepage")
    return render(request, 'home.html')

templates/footer.html
<footer class="mdl-mini-footer">
          <div class="mdl-mini-footer--left-section">
            <button class="mdl-mini-footer--social-btn social-btn social-btn__twitter">
              <span class="visuallyhidden">Twitter</span>
            </button>
            <button class="mdl-mini-footer--social-btn social-btn social-btn__blogger">
              <span class="visuallyhidden">Facebook</span>
            </button>
            <button class="mdl-mini-footer--social-btn social-btn social-btn__gplus">
              <span class="visuallyhidden">Google Plus</span>
            </button>
          </div>
          <div class="mdl-mini-footer--right-section">
            <button class="mdl-mini-footer--social-btn social-btn__share">
              <i class="material-icons" role="presentation">share</i>
              <span class="visuallyhidden">share</span>
            </button>
          </div>
        </footer>

templates/home.html
{% extends 'main_layout.html' %}

{% block title %}
    Homepage
{% endblock %}

{% block content %}

<main class="mdl-layout__content">
   <div class="mdl-grid ">

       <div class="mdl-cell mdl-cell--3-col mdl-cell--hide-tablet mdl-cell--hide-phone"></div>
       <div class="mdl-cell mdl-cell--6-col mdl-cell--8-col-tablet mdl-cell--12-col-phone"><h2>Welcome</h2></div>

   </div>
</main>

{% endblock %}

{% block before_body %}
{% endblock %}

templates/main_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="content-type" content="text/html; charset=UTF-8">
      <meta name="robots" content="noindex, nofollow">
      <meta name="googlebot" content="noindex, nofollow">
      <meta name="csrf_token" content="{% csrf_token %}">
      <title>
         {% block title %}
         {% endblock %}
      </title>
      <!--<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">-->
      <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">-->
      <!--<link rel="stylesheet" href="{% static 'floating-labels.css' %}">-->

      <!-- Material Design Lite -->
      <!-- <link rel="stylesheet" href="{% static 'css/material.indigo-pink.min.css' %}"> -->
      <link rel="stylesheet" href="{% static 'css/material.min.css' %}">

      <!--<script src="https://code.getmdl.io/1.3.0/material.min.js"></script>-->
      <!-- <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css"> -->
      
      <!-- Material Design icon font -->
      <!--<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">-->
      <link rel="stylesheet" href="{% static 'css/material_icon.css' %}">

      <!--<link rel="stylesheet" href="{% static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">-->
      <!--<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">-->
      <!--<link rel="stylesheet" href="{% static 'css/main.css' %}">-->
      <link rel="stylesheet" href="{% static 'style.css' %}">
      <!-- <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css"> -->
      {% block css %}
      {% endblock %}
   </head>
   <body>

      {% block before_main %}
      {% endblock %}

   <div class="mdl-layout__container">
      <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      {% include "navbar.html" %}
         <main class="mdl-layout__content">
         
         {% block content %}
         
         {% endblock %}
         
         </main>
         <!--{% include "footer.html" %}-->
      </div>
   </div>

         <!-- <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
         // <script src="{% static 'js/bootstrap.min.js' %}"></script> -->
         <script src="{% static 'js/material.min.js' %}"></script>
         <!-- // <script src="{% static 'js/vue.min.js' %}"></script> -->
         
         <!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>-->

      {% block before_body %}
      {% endblock %}

   </body>
</html>

templates/navbar.html
{% load static from staticfiles %}
<!-- <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header has-drawer is-upgraded" data-upgraded=",MaterialLayout"> -->
<!-- Always shows a header, even in smaller screens. -->
<header class="mdl-layout__header">
   <div class="mdl-layout__header-row">
      <!-- Title -->
      <span class="mdl-layout-title"><a href="/">Galli Foods</a></span>
      <!-- Add spacer, to align navigation to the right -->
      <div class="mdl-layout-spacer"></div>
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable
         mdl-textfield--floating-label mdl-textfield--align-right">
         <label class="mdl-button mdl-js-button mdl-button--icon" for="waterfall-exp">
            <i class="material-icons">search</i>
         </label>
         <div class="mdl-textfield__expandable-holder">
            <form role="form" method="get" id="" class="" action="{% url 'articles:search_article' %}">
                
                <input class="mdl-textfield__input" type="search" name="search" id="waterfall-exp" placeholder="search">
            </form>
         </div>
      </div>
      <!-- Navigation. We hide it in small screens. -->
      <nav class="mdl-navigation mdl-layout--large-screen-only">
         {% if user.is_authenticated %}
            <a class="mdl-navigation__link" href="{% url 'articles:create' %}">Create Article</a>
            <a class="mdl-navigation__link" href="{% url 'accounts:dashboard' %}">Dashboard</a>
            <!--<a class="mdl-navigation__link" href="javascript:void(0);">{{ user.get_username }}</a>-->
            <img src="{% static 'images/user.jpg' %}" class="nav-avatar">
          <div class="nav-avatar-dropdown">
            <span>{{ user.get_username }}</span>
            <div class="mdl-layout-spacer"></div>
            <button id="nav_dropdown" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
              <i class="material-icons" role="presentation">arrow_drop_down</i>
              <span class="visuallyhidden">Accounts</span>
            </button>
            <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="nav_dropdown">
              <li class="mdl-menu__item">

                 <span onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</span>
                     <form role="form" method="post" id="logout-form" class="logout-link" action="{% url 'accounts:logout' %}">
                        {% csrf_token %}
                     </form>
              </li>
            </ul>
          </div>
         {% else %}
            <a class="mdl-navigation__link" href="{% url 'accounts:login' %}">Login</a>
            <a class="mdl-navigation__link" href="{% url 'accounts:signup' %}">Signup</a>
         {% endif %}
         <!--<a class="mdl-navigation__link" href="">Link</a>-->
      </nav>
   </div>
</header>

<div class="mdl-layout__drawer">
   <span class="mdl-layout-title">Galli Foods</span>

   <nav class="mdl-navigation">
       <a class="mdl-navigation__link" href="">About</a>
       <a class="mdl-navigation__link" href="">Contact</a>
      {% if user.is_authenticated %}
      <a class="mdl-navigation__link" href="{% url 'articles:create' %}">Create Article</a>

      <a class="mdl-navigation__link" href="">
         <form role="form" method="post" class="logout-link" action="{% url 'accounts:logout' %}">
            {% csrf_token %}
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
               <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" type="submit">
               Logout
               </button>
            </div>
         </form>
      </a>
      {% else %}
      <a class="mdl-navigation__link" href="{% url 'accounts:login' %}">Login</a>
      <a class="mdl-navigation__link"href="{% url 'accounts:signup' %}">Signup</a>
      {% endif %}

   </nav>
</div>
<!-- </div> -->
<!--<header>-->
<!--<nav class="navbar navbar-expand-lg navbar-light bg-light">-->
<!--<a class="navbar-brand" href="/"> <img class="logo" src="http://bootstrap-ecommerce.com/main/images/logo-white.png" height="40"> LOGO</a>-->
<!--<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar1" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">-->
<!--<span class="navbar-toggler-icon"></span>-->
<!--</button>-->
<!--<div class="collapse navbar-collapse" id="navbar1">-->
<!--<ul class="navbar-nav ml-auto">-->
<!--<li class="nav-item active">-->
<!--<a class="nav-link" href="/"> Home <span class="sr-only">(current)</span></a>-->
<!--</li>-->
<!--{% if user.is_authenticated %}-->
<!--<li class="nav-item"><a class="nav-link" href="{% url 'articles:create' %}">Create Article</a></li>-->
<!--<li class="nav-item dropdown">-->
<!--<a class="nav-link  dropdown-toggle" href="#" data-toggle="dropdown">{{ user.get_username }}</a>-->
<!--<ul class="dropdown-menu">-->
<!--<li class="nav-item">-->
<!--<form role="form" method="post" class="logout-link" action="{% url 'accounts:logout' %}">-->
<!--{% csrf_token %}-->
<!--<button class="" type="submit">Logout</button>-->
<!--</form>-->
<!--</li>-->
<!--</ul>-->
<!--</li>-->
<!--{% else %}-->
<!--<li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>-->
<!--<li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a></li>-->
<!--{% endif %}-->
<!--&lt;!&ndash;<li class="nav-item"><a class="nav-link" href="html-components.html"> Documentation </a></li>&ndash;&gt;-->
<!--&lt;!&ndash;<li class="nav-item">&ndash;&gt;-->
<!--&lt;!&ndash;<a class="btn ml-2 btn-warning" href="http://bootstrap-ecommerce.com">Download</a>&ndash;&gt;-->
<!--&lt;!&ndash;</li>&ndash;&gt;-->
<!--</ul>-->
<!--</div>-->
<!--</nav>-->
<!--</header>-->

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
test
</body>
</html>